version: '3.8'
services:
  app:
    build:
      context: ./config/docker/php
    volumes:
      - .:/var/www/vc
      - vendor_data:/var/www/vendor
    depends_on:
      - db
  db:
    image: postgres:latest    
    environment:
      POSTGRES_USER: vc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vc_db
    volumes:
      - db_data:/var/lib/postgresql/data:rw
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
    - .:/var/www/vc
    - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - app
volumes:
  db_data:
  vendor_data: